<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQUbnoY1\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQUbnoY1/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/ContainerQUbnoY1.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\ContainerQUbnoY1\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \ContainerQUbnoY1\App_KernelEnvDebugContainer([
    'container.build_hash' => 'QUbnoY1',
    'container.build_id' => '9870f1e3',
    'container.build_time' => 1586794236,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQUbnoY1');
