<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXktbXEE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXktbXEE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXktbXEE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXktbXEE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXktbXEE\App_KernelDevDebugContainer([
    'container.build_hash' => 'XktbXEE',
    'container.build_id' => '7fcd0832',
    'container.build_time' => 1586857487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXktbXEE');
