<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYH599SP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYH599SP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYH599SP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYH599SP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYH599SP\App_KernelDevDebugContainer([
    'container.build_hash' => 'YH599SP',
    'container.build_id' => '04db1596',
    'container.build_time' => 1586793815,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYH599SP');
