<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'team_create' => [[], ['_controller' => 'App\\Controller\\PTTeamController::teamCreatePage'], [], [['text', '/team/create']], [], []],
    'team_creation' => [[], ['_controller' => 'App\\Controller\\PTTeamController::teamCreation'], [], [['text', '/team/create']], [], []],
    'app_ptteam_getrandompokemon' => [[], ['_controller' => 'App\\Controller\\PTTeamController::getRandomPokemon'], [], [['text', '/pokemon/random']], [], []],
    'team_edit' => [['id'], ['_controller' => 'App\\Controller\\PTTeamEditController::teamEditPage'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/team']], [], []],
    'team_edit_action' => [['id'], ['_controller' => 'App\\Controller\\PTTeamEditController::teamEditAction'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/team']], [], []],
    'team_list' => [[], ['_controller' => 'App\\Controller\\PTTeamListController::teamList'], [], [['text', '/team/list']], [], []],
    'team_list_filter' => [[], ['_controller' => 'App\\Controller\\PTTeamListController::teamListFilter'], [], [['text', '/team/list']], [], []],
];
