<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pokemon extends \App\Entity\Pokemon implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'pokemon_id', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'base_experience', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'sprite', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'abilities', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'types', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'team'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'pokemon_id', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'base_experience', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'sprite', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'abilities', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'types', '' . "\0" . 'App\\Entity\\Pokemon' . "\0" . 'team'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pokemon $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Pokemon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getPokemonId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPokemonId', []);

        return parent::getPokemonId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPokemonId(int $pokemon_id): \App\Entity\Pokemon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPokemonId', [$pokemon_id]);

        return parent::setPokemonId($pokemon_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseExperience(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseExperience', []);

        return parent::getBaseExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseExperience(int $base_experience): \App\Entity\Pokemon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseExperience', [$base_experience]);

        return parent::setBaseExperience($base_experience);
    }

    /**
     * {@inheritDoc}
     */
    public function getSprite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSprite', []);

        return parent::getSprite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSprite(?string $sprite): \App\Entity\Pokemon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSprite', [$sprite]);

        return parent::setSprite($sprite);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbilities(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbilities', []);

        return parent::getAbilities();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbilities(?array $abilities): \App\Entity\Pokemon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbilities', [$abilities]);

        return parent::setAbilities($abilities);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypes', []);

        return parent::getTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function addType(\App\Entity\Type $type): \App\Entity\Pokemon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addType', [$type]);

        return parent::addType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function removeType(\App\Entity\Type $type): \App\Entity\Pokemon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeType', [$type]);

        return parent::removeType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeam(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeam', []);

        return parent::getTeam();
    }

    /**
     * {@inheritDoc}
     */
    public function addTeam(\App\Entity\team $team): \App\Entity\Pokemon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTeam', [$team]);

        return parent::addTeam($team);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTeam(\App\Entity\team $team): \App\Entity\Pokemon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTeam', [$team]);

        return parent::removeTeam($team);
    }

}
